### ISSUE TITLE
Program creation panics if ProgramOption is nil

### ISSUE THREAD

**Issue by rhnvrm** [cel-expr/cel-go#198]
**Describe the bug**
During program creation, 
```go
	prg, err := e.Program(c)
	if err != nil {
		log.Fatalf("program creation error: %s\n", err)
	}
```

if instead we pass a nil function by mistake, the program panics,
```go
	prg, err := e.Program(c, nil)
	if err != nil {
		log.Fatalf("program creation error: %s\n", err)
	}
```

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x8fe8d2]

goroutine 1 [running]:
github.com/google/cel-go/cel.newProgram(0xc00017b180, 0xb58980, 0xc000235bc0, 0xc00023a540, 0x2, 0x2, 0x1, 0x1, 0xc000255b60, 0x40d8e8)
        /home/rhnvrm/Projects/go/pkg/mod/github.com/google/cel-go@v0.2.1-0.20190402190846-ef096d28123a/cel/program.go:100 +0x232
github.com/google/cel-go/cel.(*env).Program(0xc00017b180, 0xb58980, 0xc000235bc0, 0xc0001ff6a8, 0x1, 0x1, 0x0, 0x203000, 0x7f7a0326bd58, 0x0)
        /home/rhnvrm/Projects/go/pkg/mod/github.com/google/cel-go@v0.2.1-0.20190402190846-ef096d28123a/cel/env.go:236 +0x7d
main.main()
        /home/rhnvrm/Projects/Company/test/main.go:50 +0x125e
```

**Expected behavior**

Should instead return an error by checking if opt is nil.

In cel/program.go#97
```
	// Configure the program via the ProgramOption values.
	var err error
	for _, opt := range opts {
		p, err = opt(p)
		if err != nil {
			return nil, err
		}
	}
```

I would be happy to add a fix for this, as a first contribution to this project.

**Comment by TristonianJones** [comment]
Thanks Rohan, feel free to submit a pull request for this
