### ISSUE TITLE
in operator causes panic for map

### ISSUE THREAD

**Issue by yangminzhu** [cel-expr/cel-go#208]
**Describe the bug**
I'm not sure if I'm missing anything, the `in` operator causes panic for `map[string]string` in my test code.

**To Reproduce**
Check which components this affects:

- [ ]  parser
- [ ]  checker
- [x]  interpreter

Test setup:
```go
func Test_MyTest(t *testing.T) {
	decls := Declarations(decls.NewIdent("g", decls.NewMapType(decls.String, decls.String), nil))
	env, err := NewEnv(decls)
	if err != nil {
		t.Fatalf("environment creation error: %s\n", err)
	}

	// The following expression will trigger panic
	p, iss := env.Parse(`"g1" in g`)

	// The following expression works as expected, no panic
	// p, iss := env.Parse(`"g1" in {"g1": "g2"}`)

	if iss != nil && iss.Err() != nil {
		t.Fatal(iss.Err())
	}
	c, iss := env.Check(p)
	if iss != nil && iss.Err() != nil {
		t.Fatal(iss.Err())
	}

	prg, err := env.Program(c)
	if err != nil {
		t.Fatalf("program creation error: %s\n", err)
	}

	vars := map[string]interface{}{
		"g": map[string]string{"g1": "g2"},
	}

	// The following vars work as expected, no panic
	// vars := map[string]interface{}{
	// 	 "g": map[string]interface{}{"g1": "g2"},
	// }

	out, _, err := prg.Eval(vars)
	if err != nil {
		t.Fatalf("runtime error: %s\n", err)
	}

	if out != types.True {
		t.Errorf(`Got '%v', wanted true`, out.Value())
	}
}
```

**Actual output**
```
=== RUN   Test_MyTest
--- FAIL: Test_MyTest (0.00s)
panic: reflect: call of reflect.Value.Type on zero Value [recovered]
	panic: reflect: call of reflect.Value.Type on zero Value

goroutine 19 [running]:
testing.tRunner.func1(0xc0001ac100)
	/usr/local/go/src/testing/testing.go:792 +0x387
panic(0x984e00, 0xc000292f40)
	/usr/local/go/src/runtime/panic.go:513 +0x1b9
reflect.Value.Type(0x0, 0x0, 0x0, 0x0, 0xa)
	/usr/local/go/src/reflect/value.go:1743 +0x16c
github.com/google/cel-go/common/types.(*baseMap).Get(0xc0002a45c0, 0xaedb60, 0xc0002527e0, 0xc0002b6200, 0x7f12b60a3b70)
	/home/ymzhu/go/src/github.com/google/cel-go/common/types/map.go:180 +0x61
github.com/google/cel-go/common/types.(*baseMap).Contains(0xc0002a45c0, 0xaedb60, 0xc0002527e0, 0x0, 0x0)
	/home/ymzhu/go/src/github.com/google/cel-go/common/types/map.go:66 +0x43
github.com/google/cel-go/interpreter/functions.inAggregate(0xaedb60, 0xc0002527e0, 0x7f12b60a3b30, 0xc0002527f0, 0xc0002527f0, 0xc0002a90e0)
	/home/ymzhu/go/src/github.com/google/cel-go/interpreter/functions/standard.go:257 +0xa8
github.com/google/cel-go/interpreter.(*evalBinary).Eval(0xc000254c00, 0xae84c0, 0xc000292f20, 0xc0002b6240, 0xae84c0)
	/home/ymzhu/go/src/github.com/google/cel-go/interpreter/planner.go:926 +0x155
github.com/google/cel-go/cel.(*prog).Eval(0xc0002b11d0, 0x97c940, 0xc0002b6240, 0x1, 0xc0002a9168, 0x0, 0xae57e0, 0xc0002b11d0, 0x0)
	/home/ymzhu/go/src/github.com/google/cel-go/cel/program.go:204 +0xb0
github.com/google/cel-go/cel.Test_MyTest(0xc0001ac100)
	/home/ymzhu/go/src/github.com/google/cel-go/cel/cel_test.go:129 +0x4e2
testing.tRunner(0xc0001ac100, 0xa6dbe0)
	/usr/local/go/src/testing/testing.go:827 +0xbf
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:878 +0x35c
```

**Expected behavior**
`"g1" in g` should not panic and should return `true` for `"g": map[string]string{"g1": "g2"}`

**Additional context**
The following two cases work as expected and doesn't trigger the panic
- `"g1" in g` returns `true` for `"g": map[string]interface{}{"g1": "g2"}`
- `"g1" in {"g1": "g2"}` returns `true`

It seems the panic is caused by `m.refValue` being nil. 

https://github.com/google/cel-go/blob/a19e5a943075deca5d42d1f6eefe7862a33c3c5a/common/types/map.go#L180

**Comment by TristonianJones** [comment]
Thanks for the bug report. It looks like there's an issue with a missing `Contains` overload for the `stringMap` specialization. I'll put something together later tonight and send it out for review.

**Comment by TristonianJones** [comment]
Looks like there were also some inconsistencies in the `Contains` semantics with respect to heterogeneous equality. I'm making a few subtle changes in behavior to be consistent with the spec which is taking a bit more time than I had originally estimated. 

Specifically, `Contains` or `a in [b, c, d]` is semantically equivalent to `a == b || a == c || a == d` which means that the `Contains` operator can absorb errors due to heterogeneous equality, but may error in cases where the element does not exist in a mixed element type list. Most of the time, this won't happen, but the change in behavior will merit additional tests and a minor version release.
